version: '3'

services:
  myprometheus:
    image: prom/prometheus
    container_name: prom_1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus-af-south-1.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: Grafana_dashboards
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning


    


